# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiraslivres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='coddist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='codsubpref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
