# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiraslivres', '0002_auto_20170120_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
